### PR TITLE
CI: Add Linux build

### PR DESCRIPTION
**Pull request by terorie**
Solves #35 

Currently failing on `rvlTrkMem.c` for an unknown reason.

Since the build takes long (and consumes a lot of resources / CI minutes), we might want to set it as a manual trigger only.

### CODE REVIEW

**Comment by terorie** [comment]
Any help on solving the Wine CI failure(s) is highly welcome!

**Comment by riidefi** [comment]
Are we sure it's not just failing on the first file it compiles? There doesn't appear to be anything special about that C file.

**Comment by terorie** [comment]
@riidefi It seems to fail even in the middle of the run: https://github.com/terorie/mkw/runs/3200177080?check_suite_focus=true#step:11:726

**Comment by stblr** [comment]
Are you sure it's not failing because it doesn't find `powerpc-eabi-as` at the very end instead?

**Comment by riidefi** [comment]
I think your issue might be the "$TOOLS_URL" line. I believe the syntax is "$Env:TOOLS_URL"?

**Comment by terorie** [comment]
That's PowerShell syntax. Bash uses `$TOOLS_URL`. Ignore the last 8 CI failures, my brain is still warming up.

**Pull request merged**
