### PR TITLE
Clean up RVL/NAND

### PR DESCRIPTION
**Pull request by wait-wtf**

### CODE REVIEW

**Comment by riidefi** [comment]
Let's try to get the script doing this automatically.

**Comment by wait-wtf** [comment]
@riidefi How would the script know all the function signatures?

**Comment by riidefi** [comment]
We'd provide them. Perhaps through regexing the header?

**Comment by wait-wtf** [comment]
@riidefi Up to you, feel free to implement it.

**Comment by riidefi** [comment]
I'll merge for now

**Pull request merged**
